
CREATE TABLE public."State" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) NOT NULL
);


CREATE TABLE public."Teacher" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    mail VARCHAR(254) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    logo TEXT,
    text_1 VARCHAR(255),
    text_2 VARCHAR(255),

    id_state INTEGER NOT NULL,

    CONSTRAINT fk_teacher_state
        FOREIGN KEY (id_state)
        REFERENCES public."State"(id)
);


CREATE TABLE public."Admin" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    mail VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL
);

CREATE TABLE public."Code" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    creation_date DATE NOT NULL DEFAULT CURRENT_DATE,

    id_teacher INTEGER NOT NULL,

    CONSTRAINT fk_code_teacher
        FOREIGN KEY (id_teacher)
        REFERENCES public."Teacher"(id)
);

CREATE TABLE public."Student" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    mail VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE public."Report" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    id_code INTEGER NOT NULL,
    id_student INTEGER NOT NULL,
    downloaded_at TIMESTAMPTZ,

    CONSTRAINT fk_report_code
        FOREIGN KEY (id_code)
        REFERENCES public."Code"(id),

    CONSTRAINT fk_report_student
        FOREIGN KEY (id_student)
        REFERENCES public."Student"(id)
);

INSERT INTO public."State" (id, name)
VALUES
    (1, 'Pendiente'),
    (2, 'Aceptada'),
    (3, 'Rechazada');